#!/usr/bin/env bash
# Print a Nix derivation for a syno release, for babarot/nur-packages.
# Usage: nix-derivation.sh <version> <checksums.txt>
set -euo pipefail

version=$1
checksums=$2

sha() {
  local sum
  sum=$(awk -v f="$1" '$2 == f { print $1 }' "$checksums")
  if [[ -z $sum ]]; then
    echo "no checksum for $1 in $checksums" >&2
    exit 1
  fi
  echo "$sum"
}

# Looked up before the heredoc: a failing command substitution inside it
# would not stop the script, even with set -e
darwin_arm64=$(sha syno-darwin-arm64)
darwin_x86_64=$(sha syno-darwin-x86_64)
linux_arm64=$(sha syno-linux-arm64)
linux_x86_64=$(sha syno-linux-x86_64)

cat <<NIX
# This file was generated by syno's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "${version}";
  base = "https://github.com/babarot/syno/releases/download/\${version}";
  assets = {
    aarch64-darwin = {
      name = "syno-darwin-arm64";
      sha256 = "${darwin_arm64}";
    };
    x86_64-darwin = {
      name = "syno-darwin-x86_64";
      sha256 = "${darwin_x86_64}";
    };
    aarch64-linux = {
      name = "syno-linux-arm64";
      sha256 = "${linux_arm64}";
    };
    x86_64-linux = {
      name = "syno-linux-x86_64";
      sha256 = "${linux_x86_64}";
    };
  };
  asset = assets.\${system} or (throw "syno: unsupported system \${system}");
in
stdenvNoCC.mkDerivation {
  pname = "syno";
  inherit version;

  src = fetchurl {
    url = "\${base}/\${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # A static Go binary; stripping it again or patching it gains nothing
  dontFixup = true;

  installPhase = ''
    install -Dm755 \$src \$out/bin/syno
  '';

  meta = {
    description = "Find the Synology NAS on your network and check on it from the terminal";
    homepage = "https://github.com/babarot/syno";
    license = lib.licenses.mit;
    mainProgram = "syno";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
NIX
